module.exports = {
    sorts: [
        'relevance',
        'title',
        '-title',
        '-published_date',
        'published_date',
        '-last_updated',
        'last_updated',
        '-points',
        'points',
        '-bayesian_average',
        'bayesian_average',
        '-monthly_popularity',
        'monthly_popularity',
        'prices.USD',
        '-prices.USD',
    ],
    alias: {
        name: 'title',
        '-name': '-title',
        updated: 'last_updated',
        '-updated': '-last_updated',
        hearts: 'points',
        '-hearts': '-points',
        heart: 'points',
        '-heart': '-points',
        stars: 'points',
        '-stars': '-points',
        star: 'points',
        '-star': '-points',
        popularity: 'monthly_popularity',
        '-popularity': '-monthly_popularity',
        prices: 'prices.USD',
        '-prices': 'prices.USD',
        price: 'prices.USD',
        '-price': 'prices.USD',
    },
};
