module.exports = {
    types: [
        'all_types',
        'application',
        'webapp',
        'scope',
        'snappy',
        'snappy_application',
        'snappy_framework',
        'snappy_oem',
        'snappy_os',
        'snappy_kernel',
        'snappy_gadget',
    ],
    alias: {
        all: 'all_types',
        app: 'application',
        snap: 'snappy',
        snap_application: 'snappy_application',
        snap_app: 'snappy_application',
        snap_framework: 'snappy_framework',
        snap_oem: 'snappy_oem',
        snap_os: 'snappy_os',
        snap_kernel: 'snappy_kernel',
        snap_gadget: 'snappy_gadget',
    },
};
